name: release

on:
    workflow_dispatch

jobs:
    release:
        runs-on: macos-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: install modules
              run: npm install semantic-release @semantic-release/git @semantic-release/github -D
            - name: release
              run: npx semantic-release
              env:
                GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
