name: terraform build

on:
    push:
        branches:
            - main
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
jobs:
    terraform:
        runs-on: macos-latest
        steps:
            - name: echo
              run: echo "Running terraform"
            - name: checkout
              uses: actions/checkout@v4
            - name: instal terraform
              uses: hashicorp/setup-terraform@v3
            - name: init
              run: terraform init
            - name: validate
              run: terraform validate
            - name: fmt
              run: terraform fmt -recursive
            - name: plam
              run: terraform plan
            - name: apply
              run: terraform apply -auto-approve
